defaults:
  - physics: phys_dyn_rhoEs #physical constants
  - exp_type: TL_rhoEs #experiment_type
  - setup: setup #manual setup such as use A_isoth or self calculate based on other parameters

hydra:
  job:
    chdir: true