defaults:
  - _self_
  - physics_fp: basic #phys_old_noniso #physical constants
  - exp_type_fp: TL09 #experiment_type
# TL_nonisothermal #old_TL_noniso  #OLS_A  #CW_IRSL
# phys_old_noniso phys_optic12 phys_optic19 phys_static
  - setup: setup #manual setup such as use A_isoth or self calculate based on other parameters

hydra:
  job:
    chdir: true